export const JOURNEYS = [
  {
    id: 'temple-walk',
    name: 'Temple Walk',
    icon: '\u{1F3EF}',
    description: 'Walk through the sacred grounds',
    steps: [
      {
        id: 'torii-entrance',
        narration: 'You stand before the ancient torii gate. It marks the boundary between the ordinary world and the sacred space beyond. Take a breath and step through.',
        camera: { position: [0, 3, 16], target: [0, 2.5, 10] },
        duration: 10000,
        moodOverride: 'serene',
      },
      {
        id: 'stone-path',
        narration: 'The stone path unfolds before you, each stepping stone placed with intention. In Zen, even walking becomes meditation — each step a complete universe.',
        camera: { position: [1.5, 2, 8], target: [0, 0.5, 3] },
        duration: 10000,
        moodOverride: 'contemplative',
      },
      {
        id: 'incense-offering',
        narration: 'Incense smoke rises in delicate spirals, carrying prayers upward. The fragrance clears the mind and purifies the space between thought and silence.',
        camera: { position: [1.5, 1.5, 4.5], target: [0, 0.8, 3] },
        duration: 10000,
        moodOverride: 'serene',
      },
      {
        id: 'buddha-presence',
        narration: 'The Buddharoid awaits in stillness. Neither machine nor monk, it bridges the ancient and the digital — a guide forged in compassion and code.',
        camera: { position: [3, 2, 2], target: [0, 0.5, 0] },
        duration: 12000,
        moodOverride: 'contemplative',
      },
      {
        id: 'pagoda-wisdom',
        narration: 'The pagoda rises in three tiers, each representing a stage of awakening. Its golden spire catches the light — a reminder that enlightenment is always within reach.',
        camera: { position: [-4, 5, -2], target: [0, 4, -5] },
        duration: 10000,
        moodOverride: 'joyful',
      },
    ],
  },
  {
    id: 'zen-meditation',
    name: 'Zen Meditation',
    icon: '\u{1F9D8}',
    description: 'A guided seated meditation',
    steps: [
      {
        id: 'approach',
        narration: 'Approach the Buddharoid with an open heart. Find a comfortable position and let your body settle. The temple holds you in its ancient embrace.',
        camera: { position: [2, 2, 4], target: [0, 0.5, 0] },
        duration: 8000,
        moodOverride: 'serene',
      },
      {
        id: 'settle',
        narration: 'Close your eyes if you wish. Feel the weight of your body. Let thoughts come and go like cherry blossoms on the wind — notice them, then release.',
        camera: { position: [0, 1.5, 3], target: [0, 0.8, 0] },
        duration: 12000,
        moodOverride: 'serene',
      },
      {
        id: 'breathe',
        narration: 'Breathe in slowly through your nose. Hold gently. Breathe out through your mouth. Let each breath carry away one concern, one worry, one thought.',
        camera: { position: [0, 1.2, 2.5], target: [0, 0.8, 0] },
        duration: 20000,
        moodOverride: 'serene',
      },
      {
        id: 'return',
        narration: 'Gently bring your awareness back to the temple. Feel the ground beneath you. You carry this stillness within you always. Open your eyes when ready.',
        camera: { position: [3, 2.5, 5], target: [0, 1, 0] },
        duration: 10000,
        moodOverride: 'joyful',
      },
    ],
  },
  {
    id: 'wisdom-pilgrimage',
    name: 'Wisdom Pilgrimage',
    icon: '\u{1F4A1}',
    description: 'Visit the lanterns of wisdom',
    steps: [
      {
        id: 'lantern-1',
        narration: 'The first lantern illuminates Right Understanding. To see things as they truly are, free from delusion — this is where the path begins.',
        camera: { position: [-3, 2, 7.5], target: [-2.5, 1, 6] },
        duration: 10000,
        moodOverride: 'contemplative',
      },
      {
        id: 'lantern-2',
        narration: 'The second lantern reveals Right Intention. Let your heart be guided by compassion, not by craving. Every action begins with a thought.',
        camera: { position: [3, 2, 7.5], target: [2.5, 1, 6] },
        duration: 10000,
        moodOverride: 'contemplative',
      },
      {
        id: 'lantern-3',
        narration: 'The third lantern speaks of Right Speech. Words can heal or harm. Choose them as carefully as a gardener chooses seeds.',
        camera: { position: [-3, 2, 3.5], target: [-2.5, 1, 2] },
        duration: 10000,
        moodOverride: 'serene',
      },
      {
        id: 'lantern-4',
        narration: 'The fourth lantern embodies Right Action. Let your deeds reflect your deepest values. Harm no living being — including yourself.',
        camera: { position: [3, 2, 3.5], target: [2.5, 1, 2] },
        duration: 10000,
        moodOverride: 'serene',
      },
      {
        id: 'lantern-5',
        narration: 'The fifth lantern glows with Right Effort. The middle path — neither striving too hard nor giving up. Like tuning a string to the perfect tension.',
        camera: { position: [-3.5, 2, -0.5], target: [-3, 1, -2] },
        duration: 10000,
        moodOverride: 'energized',
      },
      {
        id: 'lantern-6',
        narration: 'The sixth lantern holds Right Mindfulness. Be present in this moment, for it is the only moment that exists. The lanterns have shared their light with you.',
        camera: { position: [3.5, 2, -0.5], target: [3, 1, -2] },
        duration: 12000,
        moodOverride: 'joyful',
      },
    ],
  },
];
