export const MOOD_PRESETS = {
  serene: {
    ambientColor: '#ffe8cc',
    ambientIntensity: 0.25,
    fogColor: '#c9b8a0',
    fogNear: 20,
    fogFar: 55,
    particleSpeed: 1.0,
    petalSpeed: 1.0,
    smokeSpeed: 1.0,
    buddhaGlowColor: '#ffaa00',
    buddhaGlowIntensity: 0.1,
    skyInclination: 0.48,
  },
  contemplative: {
    ambientColor: '#ccccee',
    ambientIntensity: 0.2,
    fogColor: '#a0a8b8',
    fogNear: 15,
    fogFar: 45,
    particleSpeed: 0.6,
    petalSpeed: 0.5,
    smokeSpeed: 0.7,
    buddhaGlowColor: '#8888ff',
    buddhaGlowIntensity: 0.15,
    skyInclination: 0.52,
  },
  joyful: {
    ambientColor: '#fff4cc',
    ambientIntensity: 0.35,
    fogColor: '#d4c8a8',
    fogNear: 25,
    fogFar: 65,
    particleSpeed: 1.5,
    petalSpeed: 1.8,
    smokeSpeed: 1.2,
    buddhaGlowColor: '#ffcc00',
    buddhaGlowIntensity: 0.3,
    skyInclination: 0.45,
  },
  solemn: {
    ambientColor: '#ccaa88',
    ambientIntensity: 0.15,
    fogColor: '#8a8070',
    fogNear: 12,
    fogFar: 35,
    particleSpeed: 0.4,
    petalSpeed: 0.3,
    smokeSpeed: 0.5,
    buddhaGlowColor: '#cc8844',
    buddhaGlowIntensity: 0.08,
    skyInclination: 0.55,
  },
  energized: {
    ambientColor: '#ffeeaa',
    ambientIntensity: 0.4,
    fogColor: '#ccbb90',
    fogNear: 25,
    fogFar: 60,
    particleSpeed: 2.0,
    petalSpeed: 2.0,
    smokeSpeed: 1.5,
    buddhaGlowColor: '#ffdd00',
    buddhaGlowIntensity: 0.35,
    skyInclination: 0.42,
  },
};
